# Generated by Django 3.2.7 on 2021-11-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211116_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='excelfileupload',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\hp\\Desktop\\collegeproject5/static/excel'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=20)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
                ('subjectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
