# Generated by Django 3.2.7 on 2021-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211117_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='excelfileupload',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\acer\\OneDrive\\Desktop\\attendence_collection-master/static/excel'),
        ),
    ]
