# Generated by Django 3.1.4 on 2021-12-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211212_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendence',
            name='students_present',
            field=models.IntegerField(default=0),
        ),
    ]
